#!/usr/bin/env python3
import os, socket, sys
path = sys.argv[-1].split(']unix://', 1)[1].split('|', 1)[0]
os.write(2, b'objc: diagnostic outside FFmpeg logging\n')
with socket.socket(socket.AF_UNIX) as stream:
    stream.connect(path)
    stream.sendall(b'0, 0, 0, 1, 5, 0x0000\n')
    os.write(1, bytes([0, 0, 1, 0x65, 42]))
