#!/usr/bin/env python3
"""Execute pinned upstream V8 value helpers and Rust wait/truncation parsers.

The fixture is generated by upstream code, not a second JS implementation.
Usage: python3 scripts/codex-parity/native-behavior.py UPSTREAM [--write]
"""
import argparse, json, os, subprocess
from pathlib import Path

PIN = '506a328dab110591d3c1449a15217596e7e9cd61'
ROOT = Path(__file__).resolve().parents[2]
p = argparse.ArgumentParser(description=__doc__)
p.add_argument('upstream', type=Path)
p.add_argument('--write', action='store_true')
p.add_argument('--target-dir', type=Path, help='Reuse a Cargo compilation cache (defaults to CARGO_TARGET_DIR when set)')
a = p.parse_args()
u = a.upstream.resolve()
assert subprocess.check_output(['git','-C',str(u),'rev-parse','HEAD'], text=True).strip() == PIN
assert not subprocess.check_output(['git','-C',str(u),'status','--porcelain','--untracked-files=no'], text=True).strip()
u = u/'codex-rs'
build = ROOT/'target/codex-native-parity-oracle'
(build/'src').mkdir(parents=True, exist_ok=True)
(build/'Cargo.toml').write_text('''[package]
name = "codex-native-parity-oracle"
version = "0.0.0"
edition = "2024"
[workspace]
[dependencies]
v8 = "=150.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
''')
wait = (u/'core/src/tools/code_mode/wait_handler.rs').read_text()
wait = wait[wait.index('#[derive(Debug, Deserialize)]'):wait.index('fn parse_arguments')]
source = r'''#![allow(dead_code, unused_imports)]
extern crate self as codex_code_mode_protocol;
extern crate self as codex_protocol;
use serde::{Deserialize,Serialize};
use serde_json::json;
const DEFAULT_WAIT_YIELD_TIME_MS: u64 = 10_000;
#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all="lowercase")]
pub enum ImageDetail {Auto,Low,High,Original}
pub const DEFAULT_IMAGE_DETAIL: ImageDetail = ImageDetail::High;
#[derive(Debug, Serialize)]
#[serde(tag="type",rename_all="snake_case")]
pub enum FunctionCallOutputContentItem {
 InputText {text: String}, InputImage {image_url: String, detail: Option<ImageDetail>}, InputAudio{audio_url:String}
}
pub mod models {pub const MAX_PROMPT_AUDIO_INPUT_BYTES: usize = 50*1024*1024;}
mod runtime {
 #[path="__AUDIO__"] pub mod audio;
 #[path="__VALUE__"] pub mod value;
 pub fn render(kind:&str, expression:&str) -> serde_json::Value {
  let isolate = &mut v8::Isolate::new(v8::CreateParams::default());
  v8::scope!(let handle_scope, isolate);
  let context = v8::Context::new(handle_scope, Default::default());
  let scope = &mut v8::ContextScope::new(handle_scope, context);
  let tc = std::pin::pin!(v8::TryCatch::new(scope));
  let mut tc = tc.init();
  let code = v8::String::new(&tc,expression).unwrap();
  let script = v8::Script::compile(&tc,code,None).unwrap();
  let input = script.run(&tc).unwrap();
  let result = match kind {
   "text" => value::serialize_output_text(&mut tc,input).map(|text| serde_json::json!({"type":"input_text","text":text})),
   "image" => value::normalize_output_image(&mut tc,input,None).map(|item| serde_json::to_value(item).unwrap()).map_err(|_| { let exception = tc.exception().unwrap(); value::value_to_error_text(&mut tc,exception) }),
   "audio" => value::normalize_output_audio(&mut tc,input).map(|item| serde_json::to_value(item).unwrap()).map_err(|_| { let exception = tc.exception().unwrap(); value::value_to_error_text(&mut tc,exception) }),
   _ => unreachable!(),
  };
  match result {Ok(item)=>serde_json::json!({"item":item}),Err(error)=>serde_json::json!({"error":error})}
 }
}
#[path="__TRUNCATE__"] mod truncate;
'''
source=source.replace('__AUDIO__',str(u/'code-mode-runtime/src/runtime/audio.rs')).replace('__VALUE__',str(u/'code-mode-runtime/src/runtime/value.rs')).replace('__TRUNCATE__',str(u/'utils/string/src/truncate.rs'))
# Only the three quoted path placeholders above are substituted.
source+=wait
source+=r'''fn main() {
 let platform=v8::new_default_platform(0,false).make_shared();
 v8::V8::initialize_platform(platform);v8::V8::initialize();
 let mut helpers=Vec::new();
 for (kind,expr) in [
 ("text","undefined"),("text","null"),("text","NaN"),("text","Infinity"),("text","-0"),("text","42n"),
 ("text","({x:undefined,n:NaN,a:[undefined,Infinity]})"),("text","({toJSON(){return 'converted'}})"),
 ("image","'data:garbage'"),("image","'DATA:image/png;base64,invalid'"),
 ("image","Object.create({image_url:'data:image/png;base64,a'})"),
 ("image","({image_url:undefined,type:'image',data:'a'})"),
 ("image","({type:'image',data:'a',mimeType:7,mime_type:'image/png'})"),
 ("image","({toJSON(){return {type:'image',data:'a'}}})"),
 ("image","({image_url:'data:image/png;base64,a',detail:'ORIGINAL'})"),
 ("image","({type:'image',data:'a',_meta:{'codex/imageDetail':'ORIGINAL'}})"),
 ("image","'https://example.invalid/a.png'"),
 ("audio","'data:garbage'"),("audio","Object.create({audio_url:'data:audio/wav;base64,a'})"),
 ("audio","({audio_url:undefined,type:'audio',data:'a'})"),
 ("audio","({type:'audio',data:'a',mimeType:7,mime_type:'audio/wav'})"),
 ] { helpers.push(json!({"kind":kind,"expression":expr,"result":runtime::render(kind,expr)})); }
 let mut waits=Vec::new();
 for input in [r#"{"cell_id":"1"}"#,r#"{"cell_id":"1","unknown":1}"#,r#"{"cell_id":"1","max_tokens":null}"#,r#"{"cell_id":"1","yield_time_ms":null}"#,r#"{"cell_id":"1","yield_time_ms":18446744073709551615}"#,r#"{"cell_id":"1","max_tokens":0,"terminate":true}"#,r#"{"cell_id":"1","terminate":null}"#] {
  let result=serde_json::from_str::<ExecWaitArgs>(input).map(|x| json!({"yield_time_ms":x.yield_time_ms,"max_tokens":x.max_tokens,"terminate":x.terminate}));
  waits.push(json!({"input":input,"result":match result {Ok(x)=>json!({"parsed":x}),Err(e)=>json!({"error":e.to_string()})}}));
 }
 let mut truncations=Vec::new();
 for text in ["abcdefghi","🦀🦀🦀🦀🦀","é中🙂abc\nlast"] { for tokens in [0,1,2,3,100] {
  truncations.push(json!({"text":text,"tokens":tokens,"result":truncate::truncate_middle_with_token_budget(text,tokens).0}));
 }}
 println!("{}",json!({"upstream":"__PIN__","helpers":helpers,"waits":waits,"truncations":truncations}));
}
'''
source=source.replace('__PIN__', PIN)
(build/'src/main.rs').write_text(source)
env=os.environ.copy()
env['CARGO_TARGET_DIR']=str(a.target_dir.resolve()) if a.target_dir else env.get('CARGO_TARGET_DIR', str(build/'target'))
output=subprocess.check_output(['cargo','run','--quiet','--manifest-path',str(build/'Cargo.toml')],env=env,text=True)
value=json.loads(output)
fixture=ROOT/'crates/nanocodex-tools/src/code_mode/native-behavior.json'
if a.write: fixture.write_text(json.dumps(value,indent=2,ensure_ascii=False)+'\n')
else: assert json.loads(fixture.read_text())==value,'native upstream behavior fixture differs'
print(f'Verified {len(value["helpers"])} upstream V8 helper, {len(value["waits"])} wait parser, and {len(value["truncations"])} truncation cases')
